name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Bundle
        run: pnpm bundle

      - name: Check lint
        run: pnpm lint

      - name: test
        shell: bash
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          pnpm test

      - name: Upload bundle
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build,config"
          target: ~/nest-app

  restart-server:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: restart server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 restart all

  ping-on-slack:
    runs-on: ubuntu-latest
    needs: restart-server
    if: always()
    steps:
      - name: Set Emoji
        id: set-emoji
        run: |
          if [ ${{ needs.restart-server.result }} = "success" ]; then
            echo "EMOJI=:tada:" >> $GITHUB_OUTPUT
          else
            echo "EMOJI=:bangbang:" >> $GITHUB_OUTPUT
          fi

      - name: post to a Slack channel
        env:
          EMOJI: ${{ steps.set-emoji.outputs.EMOJI }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C063UHSFAQ7"
          payload: |
            {
                "text": "${{env.EMOJI}} Deployment workflow",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{env.EMOJI}} Deployment process is ${{ needs.restart-server.result }}\n${{ github.event.pull_request.html_url }}"
                        }
                    }
                ]
            }
